name: Feature request
description: Suggest a new feature or change to an existing feature
labels: ["suggestion"]

body:
  - type: textarea
    id: related-problem
    attributes:
      label: Is your feature request related to a problem? If so, please describe.
      description: A clear and concise description of what the problem is.
      placeholder: I am frustrated when X happens! I think X feature would make this experience more enjoyable.
    validations:
      required: false
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature / change to an existing feature
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternative-solutions
    attributes:
      label: Describe any alternatives you have considered
      description: A clear and concise description of any alternative solutions you have considered.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any additional context about the feature request here, such as screenshots or proof of concepts.
    validations:
      required: false
