name: Add pull requests to project

on:
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add pull request to project
    runs-on: ubuntu-latest
    steps:
      - name: Add To GitHub projects
        uses: actions/add-to-project@v0.3.0
        with:
          # URL of the project to add issues to
          project-url: https://github.com/users/AyUpItsAli/projects/3
          # A GitHub personal access token with write access to the project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
